Networking basics

diff --git a/0x07-networking_basics/5-is_the_host_on_the_network b/0x07-networking_basics/5-is_the_host_on_the_network
--- a/0x07-networking_basics/5-is_the_host_on_the_network
+++ b/0x07-networking_basics/5-is_the_host_on_the_network
@@ -1,18 +1,11 @@
 #!/usr/bin/env bash
-# Script: 5-is_the_host_on_the_network
 # Description: Pings an IP address passed as an argument
-
-# Check if exactly one argument is provided
 if [ "$#" != 1 ]; then
-    echo "Error: Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
-    exit 1
+	echo "Error: Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
+	exit 1
 fi
-
-# Validate if the argument is a valid IP address
 if ! [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-    echo "Error: '$1' is not a valid IP address"
-    exit 1
+	echo "Error: '$1' is not a valid IP address"
+	exit 1
 fi
-
-# Perform ping with 5 packets
 ping -c 5 "$1"
